export const FETCH_COUNTRIES_PENDING = 'FETCH_COUNTRIES_PENDING';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_ERROR = 'FETCH_COUNTRIES_ERROR';

export const FETCH_CITIES_PENDING = 'FETCH_CITIES_PENDING';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR';

export const FETCH_CITY_POPULATION_PENDING = 'FETCH_CITY_POPULATION_PENDING';
export const FETCH_CITY_POPULATION_SUCCESS = 'FETCH_CITY_POPULATION_SUCCESS';
export const FETCH_CITY_POPULATION_ERROR = 'FETCH_CITY_POPULATION_ERROR';

export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const SORT_COUNTRIES = 'SORT_COUNTRIES';

export const FILTER_CITIES = 'FILTER_CITIES';
export const SORT_CITIES = 'SORT_CITIES';
export const ADD_CITY_TO_FAVORITES = 'ADD_CITY_TO_FAVORITES';
export const SORT_FAVORITE_CITIES = 'SORT_FAVORITE_CITIES';
export const FILTER_COUNTRIES_BY_COORDS = 'FILTER_COUNTRIES_BY_COORDS';
